insert into personajes (nombre, login, tipo, raza, sexo) values ('warrior', 'cgaley0', 'guerrero', 'argoniano', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('gandalf', 'fogdahl1', 'mago', 'caballero oscuro', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('darkside', 'mluchetti2', 'guerrero', 'nordico', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Hester', 'wtimblett3', 'picaro', 'nordico', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Corbie', 'pmcileen4', 'picaro', 'elfo', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Salvador', 'cpedrol5', 'picaro', 'elfo', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('ereborng', 'dkilian6', 'mago', 'elfo', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Agatha', 'reardley7', 'guerrero', 'argoniano', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Deadmouth', 'cscarff8', 'guerrero', 'caballero oscuro', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('ragnar', 'mnast9', 'mago', 'nordico', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Leilla', 'jbontofta', 'mago', 'caballero oscuro', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Ashton', 'cmalloyb', 'picaro', 'caballero oscuro', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Cammy', 'cdamettic', 'mago', 'argoniano', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('ferro', 'kmcgaugied', 'guerrero', 'elfo', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Carolus', 'cbanfille', 'guerrero', 'elfo', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Turner', 'goppyf', 'mago', 'nordico', 'M');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Goldie', 'jkivellg', 'picaro', 'elfo', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('trogloff', 'lbannerh', 'mago', 'nordico', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('titan', 'tgunbiei', 'guerrero', 'nordico', 'F');
insert into personajes (nombre, login, tipo, raza, sexo) values ('Sparrow', 'ihindmoorj', 'picaro', 'argoniano', 'M');
